require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Include:
    - '**/Appraisals'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'lib/generators/enumerate_it/enum/templates/**/*'

Metrics/LineLength:
  Max: 100

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Exclude:
    - 'lib/enumerate_it/class_methods.rb'
