language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/activesupport_3_0.gemfile
  - gemfiles/activesupport_3_1.gemfile
  - gemfiles/activesupport_3_2.gemfile
  - gemfiles/activesupport_4_0.gemfile
  - gemfiles/activesupport_4_1.gemfile
  - gemfiles/activesupport_4_2.gemfile
  - gemfiles/activesupport_5_0.gemfile
