language: ruby

sudo: false

cache: bundler

script: bundle exec rake spec

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  # Rails 5 requires Ruby version 2.2+
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5.0.gemfile
